### ISSUE TITLE
bug in package.json

### ISSUE THREAD

**Issue by iemwill** [scaffold-eth/scaffold-eth-typescript-challenges#16]
Line 17 should end with `node",` instead of `chain",`.

**Comment by subject026** [comment]
I was going to submit a PR for this but it doesn't look as though there is a script called "node" in the hardhat workspace.

I am probably missing something but it looks to me as though the node and chain scripts would both be for starting a local node. Not sure if they are both necessary?

**Comment by ZakGriffith** [comment]
Good find, updated in the challenges
