### ISSUE TITLE
bug: yarn watch is using watch.js

### ISSUE THREAD

**Issue by kfern** [scaffold-eth/scaffold-eth-typescript-challenges#42]
Hi! yarn watch is using watch.js

`
yarn watch
`

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/home/scaffold-eth-typescript-challenges/packages/hardhat-ts/scripts/watch.js'

**Comment by ZakGriffith** [comment]
Fixed with the merged PR, thank you!
