### ISSUE TITLE
test: Challenge 0 - Simple NFT Example Waiting for confirmation...

### ISSUE THREAD

**Issue by kfern** [scaffold-eth/scaffold-eth-typescript-challenges#44]
HI! 

The "Challenge 0 - Simple NFT Example" test does not work for me. It does not go beyond "Waiting for confirmation...".

Do I need to do something else? 

`
yarn test
`

 Challenge 0: 🎟 Simple NFT Example 🤓
    YourCollectible
      ✓ Should deploy YourCollectible (284ms)
      mintItem()
          🧑‍🏫 Tester Address:  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
          ⚖️ Starting balance:  0
          🔨 Minting...
          🏷  mint tx:  0x30672a2f684c8d8ed69e88c2661f3890a30d85d909f7b94eba62ace58f4e43d8
          ⏳ Waiting for confirmation...

![image](https://user-images.githubusercontent.com/1898891/163693209-f97f1dc5-b90e-4d5f-acfd-cab32f7afe3c.png)

`
lsb_release -a
`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

`
node -v
`
v16.13.2

**Comment by kfern** [comment]
Hi! Tests don't fail when I change

`const txResult = await mintResult.wait(2);` to `const txResult = await mintResult.wait();` at https://github.com/scaffold-eth/scaffold-eth-typescript-challenges/blob/291aa315dba1bf9d820decebdbb2bc0a6694b23c/packages/hardhat-ts/test/challenge_0.ts#L53

Is it a typo? https://docs.ethers.io/v5/api/providers/types/#providers-TransactionResponse

**Comment by ZakGriffith** [comment]
Thank you for finding this!  I am actually surprised it hasn't been more of issue.
