### ISSUE TITLE
Failing test in challenge-1 due to unnecessary contract execute call

### ISSUE THREAD

**Issue by bill0x2A** [scaffold-eth/scaffold-eth-typescript-challenges#50]
This is the second milestone test for challenge-1: _Should redeploy Staker, stake, not get enough, and withdraw_.
The test calls the `execute` function - which is required to fail if the threshold has not been reached and therefore cannot be run in the same test as withdraw - which is required to succeed if the threshold has not been reached.
This causes the transaction to revert and the test to fail despite the contract fulfilling the criteria.
Calling execute is not mentioned in the test description so it is either there by mistake or is out of the scope of the test?

[Link to relevant code](https://github.com/scaffold-eth/scaffold-eth-typescript-challenges/blob/challenge-1-decentralized-staking/packages/hardhat-ts/test/challenge-1.ts#L123-L125)

**Comment by DariusPrzydzial** [comment]
Quest submission fails due to the above, please double-check  @ZakGriffith
