### ISSUE TITLE
Checkpoint 3: 🔑 Rigged Contract (⚔️ Side Quest)

### ISSUE THREAD

**Issue by TheNuelgeek** [scaffold-eth/scaffold-eth-typescript-challenges#59]
1. [ ] Uncomment the code in `App.jsx `to show a riggedRoll button and contract balance on the main UI tab. Now

Change `App.jsx ` to `App.tsx`

2. Add a new comment under side quest 
[ ] Uncomment the code in `01_deploy_riggedRoll.ts` to deploy riggedRoll contract.

**Comment by ZakGriffith** [comment]
Done, thank you.  Good finds.
