### ISSUE TITLE
cannot install packages

### ISSUE THREAD

**Issue by pokhrelanmol** [scaffold-eth/scaffold-eth-typescript-challenges#65]
I cloned a repo and after switching branch, I tried to install packages with yarn install but it's giving me some weird error 

Below is the exact image showing the error in my terminal

![Screenshot from 2022-10-26 07-24-31](https://user-images.githubusercontent.com/75737628/197916397-08c6866d-8d44-4a0a-bb11-df1aaaaa2964.png)

**Comment by ZakGriffith** [comment]
You could try deleting the challenge folder and starting again with the clone, checkout, install and see if that helps.  Also feel free to join the specific challenge's Telegram channel and ask for help if the issues hasn't resolved.  There is a link in the readme.

**Comment by pokhrelanmol** [comment]
I found it was due to the yarn cache. Thanks for the response
